image: bradrydzewski/node:0.10
script:
    - chmod -R a+x node_modules
    - npm rebuild
    - npm install
    - npm install -g bower
    - bower install
    - grunt deploy
    - npm install -g protractor@1.3.1
    - npm install selenium-standalone@latest -g
    - apt-get install -y default-jre
    - start-selenium &
    - node server &
    - sleep 5
    - protractor protractor.js
notify:
    email:
        recipients:
            - jarrett.widman@vokalinteractive.com
