image: docker.vokal.io/node-testing
env:
    - AWS_ACCESS_KEY=$$awsAccessKey
    - AWS_SECRET_KEY=$$awsSecretKey
    - AWS_BUCKET=$$awsBucket
    - AWS_DISTRO_ID=$$awsDistroId
    - BOWER_LOGIN=$$bowerLogin
    - BOWER_OAUTH=$$bowerOauth
script:
    - echo "machine github.com" > ~/.netrc
    - echo "login $BOWER_LOGIN" >> ~/.netrc
    - echo "password $BOWER_OAUTH" >> ~/.netrc
    - git config --global url."https://github".insteadOf git://github
    - npm install
    - bower --allow-root install
    - chmod +x run-build.sh
    - ./run-build.sh
# cloudfront deployment, commented out in seed project
# deploy:
#    bash:
#        script:
#            - grunt deploy --aws-access-key-id=$AWS_ACCESS_KEY --aws-secret-access-key=$AWS_SECRET_KEY --aws-s3-bucket=$AWS_BUCKET --aws-cloudfront-distribution-id=$AWS_DISTRO_ID --gitver=$(git rev-parse --short HEAD)
notify:
    email:
        recipients:
            - jarrett.widman@vokal.io # use specific project maintainers as needed