image: bradrydzewski/node:0.10
script:
script:
   - npm install
   - npm install -g protractor@1.3.1
   - npm install -g phantomjs@1.9.10
   - webdriver-manager update
   - webdriver-manager start &
   - sleep 5
   - npm start &
   - sleep 5
   - protractor protractor.js
notify:
    email:
        recipients:
            - chris.marshall@vokalinteractive.com