image: docker.vokalinteractive.com/node-testing
env:
    - AWS_ACCESS_KEY=$$awsAccessKey
    - AWS_SECRET_KEY=$$awsSecretKey
    - AWS_BUCKET=$$awsBucket
    - AWS_DISTRO_ID=$$awsDistroId
script:
    - npm install
    - node ./node_modules/protractor/bin/webdriver-manager update
    - bower --allow-root install
    - grunt default
    - chmod +x run-build.sh
    - ./run-build.sh
deploy:
    bash:
        script:
            - grunt deploy --aws-access-key-id=$AWS_ACCESS_KEY --aws-secret-access-key=$AWS_SECRET_KEY --aws-s3-bucket=$AWS_BUCKET --aws-cloudfront-distribution-id=$AWS_DISTRO_ID --gitver=$(git rev-parse --short HEAD)
