image: docker.vokalinteractive.com/node-testing
script:
    - npm install
    - node ./node_modules/protractor/bin/webdriver-manager update
    - bower --allow-root install
    - grunt default
    - chmod +x run-build.sh
    - ./run-build.sh
