image: bradrydzewski/node:0.10
script:
#    - chmod -R a+x node_modules
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
    - npm rebuild
    - npm install
    - npm install -g grunt-cli
    - npm install -g bower
    - npm install -g protractor@1.3.1
    - npm install selenium-standalone@latest -g
    - bower install
    - grunt deploy
    - sudo apt-get install -y default-jre
    - xvfb-run --server-args="-screen 0, 1366x768x24" start-selenium &
    - node server &
    - sleep 5
    - protractor protractor.js
notify:
    email:
        recipients:
            - jarrett.widman@vokalinteractive.com
