image: docker.vokalinteractive.com/node
script:
    - apt-get install wget
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y openjdk-7-jre google-chrome-stable xvfb unzip
    - npm rebuild
    - npm install
    - npm install -g grunt-cli
    - npm install -g bower
    - npm install -g protractor@1.3.1
    - npm install -g selenium-standalone@latest
    - bower install
    - grunt deploy
    - export DISPLAY=:10
    - Xvfb :10 -screen 0 1366x768x24 -ac &
    - sleep 2
    - google-chrome --remote-debugging-port=9222 &
    - sleep 2
    - start-selenium &
    - sleep 2
    - node server &
    - sleep 2
    - protractor protractor.js
notify:
    email:
        recipients:
            - jarrett.widman@vokalinteractive.com
